FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# AGP

AGP es una API 


# GET /message
+ Response 200 (text/plain)

        Hola Mundo!
        
# PUT /message_put
    + Request id1 (application/json) {
        "Mensaje": "Hola con PUT"
    }

+ Response 204