FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# AGP

AGP es una API 


# GET /holaMundo
+ Response 200 (text/plain)

        Hola Mundo!
        
# PUT /holaMundo_Put
    + Request  (text/plain)
        Hola Mundo con PUT

+ Response 204